### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by FloooD** [FloooD/custom_cs2dsrv#17]
what's it gonna be like?

same boring addhook() + parse()?
:P

**Comment by leegao** [comment]
well I'm definitely going to write the entire parse routine as Lua hooked into C. For the rest, I'll use addhook since they're really easy to implement and then add on other features when we think of them (I'll probably also make it so that the extra features can be turned off with a --strict flag to get compliance with that other piece of software :P)

I'm open to ideas though

**Comment by leegao** [comment]
yo are we gonna continue work on the server?

**Comment by FloooD** [comment]
ya i'm just feeling lazy ;d

**Comment by leegao** [comment]
lol, k I already have the hook system set up, just need to add in all of the hooks.

**Comment by FloooD** [comment]
well i'm pretty sure you can't even do half the hooks cuz stuff like startround, endround, mapchange, serveraction, etc don't even exist lol

**Comment by leegao** [comment]
sorry mate, been a bit lazy with college work piling up, I'll start updating again later on

**Comment by FloooD** [comment]
lol same
midterm + paper on thursday
midterm on monday
yayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by FloooD** [comment]
eh@netbook:~/c$ time make
gcc -O3 -lm -lrt -I"include" -I"lua/src" src/_.c lua/src/_.c -o bin/custom_cs2dsrv
/tmp/cc5Bgjyo.o: In function `os_tmpname':
loslib.c:(.text+0x46): warning: the use of`tmpnam' is dangerous, better use `mkstemp'

real    0m36.241s
user    0m34.442s
sys 0m1.480s

wow my netbook is slow. wait i think it's just the lua lol...

**Comment by leegao** [comment]
no, it's the lua, slow make for me too so I just build from eclipse now <_<, hence we should probably switch over to a static link

**Comment by FloooD** [comment]
eh sure.. waiting 40 seconds to test something out sucks

**Comment by leegao** [comment]
Alright, I couldn't link in statically since networking depends on a dynamic library. Anyways, make will default to building using the dynamic library. Since the dll/so is a little bit altered from the standard distribution of lua, we can't actually install the library. So when you're testing, use the default build (note that you will need to execute "./run" instead of "bin/custom_server" now since we need to explicitly set the path for the lua library. (This isn't an issue in non-shared build)

Make options:
all: (default)
non-shared: (production)

Changes in lee_experimental
